[package]
name = "first"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { git = "https://github.com/rust-sdl2/rust-sdl2" }
gl = { git = "https://github.com/bjz/gl-rs" }
